[package]
name = "sample"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = { version = "0.15.3", default-features = false, features = ["allocator"] }
ckb-musl-rs = { path = ".." }

[build-dependencies]
cc = "1"

[dev-dependencies]
ckb-testtool = "0.10.2"
serde_json = "1.0"
